const W=7,H=12,RIVER=Array.from({length:14},(_,i)=>35+i),BRIDGES=[36,37,39,40,43,44,46,47],MAX_TURNS=60;
const CARDS={
 iron_guard:{name:"Iron Guard",icon:"⚔️",cost:3,kind:"unit",hp:10,damage:2,move:1,range:1,desc:"균형형 근접 유닛"},
 wind_archer:{name:"Wind Archer",icon:"🏹",cost:3,kind:"unit",hp:5,damage:2,move:1,range:3,desc:"원거리 공격"},
 stone_brute:{name:"Stone Brute",icon:"🗿",cost:5,kind:"unit",hp:17,damage:3,move:1,range:1,towerOnly:true,desc:"타워 우선 중장갑"},
 spark_runners:{name:"Spark Runners",icon:"⚡",cost:2,kind:"unit",hp:3,damage:1,move:2,range:1,count:2,desc:"빠른 유닛 2기"},
 shield_bearer:{name:"Shield Bearer",icon:"🛡️",cost:4,kind:"unit",hp:13,damage:1,move:1,range:1,shield:2,desc:"첫 피해 2 감소"},
 siege_crawler:{name:"Siege Crawler",icon:"🐢",cost:4,kind:"unit",hp:8,damage:3,move:1,range:3,towerOnly:true,desc:"원거리 타워 공격"},
 meteor_shard:{name:"Meteor Shard",icon:"☄️",cost:4,kind:"spell",damage:3,desc:"중심·인접 적 피해"},
 renewal_field:{name:"Renewal Field",icon:"✨",cost:3,kind:"spell",heal:3,desc:"중심·인접 아군 회복"}
};
const DECK=Object.keys(CARDS),TOWER_ICON={left:"♜",right:"♜",core:"♛"};
const starterCode=`function chooseAction(state, me) {
  const actions = state.legalActions;

  // 1. 주문으로 적 타워를 파괴할 수 있으면 사용합니다.
  const lethalSpell = actions.find(action => {
    if (action.type !== "play" || action.cardId !== "meteor_shard") return false;
    return state.towers.some(tower =>
      tower.owner !== me && tower.hp > 0 && tower.hp <= 2 &&
      Math.abs(Math.floor(tower.position / state.boardWidth) - Math.floor(action.position / state.boardWidth)) +
      Math.abs(tower.position % state.boardWidth - action.position % state.boardWidth) <= 1
    );
  });
  if (lethalSpell) return lethalSpell;

  // 2. 유닛 카드는 상대 타워와 가까운 합법 위치에 배치합니다.
  const unitActions = actions.filter(action =>
    action.type === "play" && state.cards[action.cardId].kind === "unit"
  );
  if (unitActions.length) {
    return unitActions.sort((a, b) => {
      const rowA = Math.floor(a.position / state.boardWidth);
      const rowB = Math.floor(b.position / state.boardWidth);
      return me === "P1" ? rowA - rowB : rowB - rowA;
    })[0];
  }

  // 3. 사용할 카드가 없으면 패스합니다.
  return actions.find(action => action.type === "pass");
}`;
const docs=`[LLM 작업]\n턴제 카드 아레나의 JavaScript AI를 작성하세요.\n\n[출력 함수]\nfunction chooseAction(state, me)\n- state.legalActions의 객체 또는 동일한 id의 객체를 반환합니다.\n- 가능한 액션은 카드+위치인 play 또는 pass뿐입니다.\n- state를 변경하지 말고 외부 API·비동기 함수를 사용하지 마세요.\n- 한 행동 제한은 500ms입니다.\n\n[액션]\n{ id:"play:iron_guard:36", type:"play", cardId:"iron_guard", position:36 }\n{ id:"pass", type:"pass" }\n\n[핵심 규칙]\n- 12×7 보드입니다. 강은 35~48의 두 줄이고, 왼쪽 다리는 36·37·43·44, 오른쪽 다리는 39·40·46·47입니다.\n- 이동 방향 앞에 아군이 있고 마지막 아군 뒤가 비어 있으면 대형을 연쇄적으로 한 칸 밀며 전진합니다.\n- 시작 에너지 5, 최대 10, 턴마다 2 회복, 31턴부터 3 회복.\n- 덱 8장, 손패 4장. 카드를 사용하면 순환하고 패스하면 유지됩니다.\n- 유닛 배치 또는 주문 사용 뒤 양측 유닛과 타워가 자동 행동합니다.\n- 좌우 보루 파괴 1점, 본진 Core 파괴 즉시 승리, 최대 60턴.\n- state에는 boardWidth, boardHeight, energy, hands, nextCards, units, towers, cards, legalActions가 있습니다.\n\n[카드]\n${Object.entries(CARDS).map(([id,c])=>`- ${id}: 비용 ${c.cost}, ${c.desc}`).join("\n")}\n\n[응답 형식]\n설명 없이 완성된 JavaScript 코드만 하나의 코드 블록으로 출력하세요. 전체를 한 번에 복사해 붙여넣을 수 있어야 합니다.\n\n[예제]\n\`\`\`javascript\n${starterCode}\n\`\`\``;
const $=id=>document.getElementById(id);let state=null,running=false,human=false,selectedCard=null,lastCell=-1,lastReplay=[],replayIndex=0,replayTimer=null,replaying=false,unitSeq=0;
function tower(id,owner,type,position,hp,damage){return{id,owner,type,position,hp,maxHp:hp,damage,range:2}}
function shuffledDeck(rng=Math.random){const deck=[...DECK];for(let i=deck.length-1;i>0;i--){const j=Math.floor(rng()*(i+1));[deck[i],deck[j]]=[deck[j],deck[i]]}return deck}
function initial(rng=Math.random){unitSeq=0;const p1=shuffledDeck(rng),p2=shuffledDeck(rng);return{turn:1,currentPlayer:"P1",energy:{P1:3,P2:3},hands:{P1:p1.slice(0,4),P2:p2.slice(0,4)},queues:{P1:p1.slice(4),P2:p2.slice(4)},units:[],towers:[tower("P2-left","P2","left",9,12,2),tower("P2-right","P2","right",11,12,2),tower("P2-core","P2","core",3,20,3),tower("P1-left","P1","left",72,12,2),tower("P1-right","P1","right",74,12,2),tower("P1-core","P1","core",80,20,3)],lastActions:[]}}
function clone(s){return JSON.parse(JSON.stringify(s))}function rc(i){return[Math.floor(i/W),i%W]}function pos(r,c){return r*W+c}function inside(r,c){return r>=0&&r<H&&c>=0&&c<W}function foe(p){return p==="P1"?"P2":"P1"}function aliveUnits(s){return s.units.filter(u=>u.hp>0)}function aliveTowers(s){return s.towers.filter(t=>t.hp>0)}function occupied(s,p){return aliveUnits(s).some(u=>u.position===p)||aliveTowers(s).some(t=>t.position===p)}function dist(a,b){const[ar,ac]=rc(a),[br,bc]=rc(b);return Math.abs(ar-br)+Math.abs(ac-bc)}
function deploymentPositions(s,player,card){if(card.kind==="spell")return Array.from({length:W*H},(_,i)=>i);const out=[];for(let i=0;i<W*H;i++){const row=rc(i)[0],own=player==="P1"?row>=7:row<=4;if(own&&!occupied(s,i))out.push(i)}const opp=foe(player),advanced=player==="P1"?[43,44,46,47]:[36,37,39,40];if(!s.towers.find(t=>t.id===`${opp}-left`&&t.hp>0))for(const i of advanced.slice(0,2))if(!occupied(s,i))out.push(i);if(!s.towers.find(t=>t.id===`${opp}-right`&&t.hp>0))for(const i of advanced.slice(2))if(!occupied(s,i))out.push(i);return out}
function legalActions(s,player){const out=[{id:"pass",type:"pass"}];for(const cardId of s.hands[player]){const card=CARDS[cardId];if(card.cost>s.energy[player])continue;for(const position of deploymentPositions(s,player,card))out.push({id:`play:${cardId}:${position}`,type:"play",cardId,position})}return out}
function cycleCard(s,p,cardId){const i=s.hands[p].indexOf(cardId),next=s.queues[p].shift();s.hands[p][i]=next;s.queues[p].push(cardId)}
function area(center){const[r,c]=rc(center),out=[];for(let dr=-1;dr<=1;dr++)for(let dc=-1;dc<=1;dc++)if(Math.abs(dr)+Math.abs(dc)<=1&&inside(r+dr,c+dc))out.push(pos(r+dr,c+dc));return out}
function deploy(s,p,cardId,position,events){const card=CARDS[cardId];s.energy[p]-=card.cost;cycleCard(s,p,cardId);if(card.kind==="spell"){const cells=area(position);if(card.damage){for(const u of aliveUnits(s).filter(x=>x.owner!==p&&cells.includes(x.position))){u.hp-=card.damage;events.push(`${card.icon} ${u.id} -${card.damage}`)}for(const t of aliveTowers(s).filter(x=>x.owner!==p&&cells.includes(x.position))){t.hp-=2;events.push(`${card.icon} ${t.id} -2`)}}else for(const u of aliveUnits(s).filter(x=>x.owner===p&&cells.includes(x.position))){const before=u.hp;u.hp=Math.min(u.maxHp,u.hp+card.heal);if(u.hp>before)events.push(`${card.icon} ${u.id} +${u.hp-before}`)}}else{const spots=[position,...neighbors(position).filter(x=>!occupied(s,x))];for(let n=0;n<(card.count||1);n++){const place=spots[n];if(place===undefined)break;s.units.push({id:`${p}-${cardId}-${++unitSeq}`,owner:p,cardId,position:place,hp:card.hp,maxHp:card.hp,damage:card.damage,move:card.move,range:card.range,towerOnly:!!card.towerOnly,shield:card.shield||0});events.push(`${card.icon} ${place} 배치`)}}}
function neighbors(i){const[r,c]=rc(i),out=[];for(const[dr,dc]of[[-1,0],[1,0],[0,-1],[0,1]])if(inside(r+dr,c+dc)){const n=pos(r+dr,c+dc);if(!RIVER.includes(n)||BRIDGES.includes(n))out.push(n)}return out}
function nearest(list,from){return [...list].sort((a,b)=>dist(from,a.position)-dist(from,b.position)||a.hp-b.hp)[0]}
function targetFor(s,u){const enemyUnits=aliveUnits(s).filter(x=>x.owner!==u.owner),enemyTowers=aliveTowers(s).filter(x=>x.owner!==u.owner),valid=u.towerOnly?enemyTowers:[...enemyUnits,...enemyTowers];return nearest(valid,u.position)}
function pushChain(s,unit,next){const blocker=aliveUnits(s).find(x=>x.position===next);if(!blocker||blocker.owner!==unit.owner)return false;const[ur,uc]=rc(unit.position),[nr,nc]=rc(next),br=nr+(nr-ur),bc=nc+(nc-uc);if(!inside(br,bc))return false;const beyond=pos(br,bc);if((RIVER.includes(beyond)&&!BRIDGES.includes(beyond))||aliveTowers(s).some(t=>t.position===beyond))return false;const chained=aliveUnits(s).find(x=>x.position===beyond);if(chained&&chained.owner!==unit.owner)return false;if(chained&&!pushChain(s,blocker,beyond))return false;blocker.position=beyond;lastCell=beyond;return true}
function stepToward(s,u,target){for(let step=0;step<u.move;step++){if(dist(u.position,target.position)<=u.range)break;const options=neighbors(u.position).filter(p=>{const block=aliveUnits(s).find(x=>x.position===p);return!aliveTowers(s).some(t=>t.position===p)&&(!block||block.owner===u.owner)}).sort((a,b)=>dist(a,target.position)-dist(b,target.position));if(!options.length||dist(options[0],target.position)>=dist(u.position,target.position))break;const next=options[0],blocker=aliveUnits(s).find(x=>x.position===next);if(blocker&&!pushChain(s,u,next))break;u.position=next;lastCell=u.position}}
function hit(attacker,target,events){let damage=attacker.damage;if(target.shield>0){const blocked=Math.min(target.shield,damage);target.shield-=blocked;damage-=blocked}target.hp-=damage;events.push(`${CARDS[attacker.cardId]?.icon||"🏰"} ${target.id} -${damage}`);lastCell=target.position}
function battlePhase(s,first,events){for(const player of[first,foe(first)])for(const id of aliveUnits(s).filter(u=>u.owner===player).map(u=>u.id)){const u=aliveUnits(s).find(x=>x.id===id);if(!u)continue;let target=targetFor(s,u);if(!target)continue;if(dist(u.position,target.position)<=u.range)hit(u,target,events);else{stepToward(s,u,target);target=targetFor(s,u);if(target&&dist(u.position,target.position)<=u.range&&u.cardId==="spark_runners")hit(u,target,events)}}for(const player of[first,foe(first)])for(const t of aliveTowers(s).filter(x=>x.owner===player)){const target=nearest(aliveUnits(s).filter(u=>u.owner!==player&&dist(u.position,t.position)<=t.range),t.position);if(target)hit({...t,cardId:null},target,events)}s.units=s.units.filter(u=>u.hp>0)}
function startTurn(s){const gain=s.turn>=31?3:2;s.energy[s.currentPlayer]=Math.min(10,s.energy[s.currentPlayer]+gain)}
function applyAction(s,action){const n=clone(s),p=n.currentPlayer,events=[];if(action.type==="play")deploy(n,p,action.cardId,action.position,events);else events.push(`${p} PASS`);battlePhase(n,p,events);n.lastActions=events;n.currentPlayer=foe(p);n.turn++;startTurn(n);return n}
function outcome(s){const p1c=s.towers.find(t=>t.id==="P1-core"),p2c=s.towers.find(t=>t.id==="P2-core");if(p1c.hp<=0)return{winner:"P2",reason:"P1 Core 파괴"};if(p2c.hp<=0)return{winner:"P1",reason:"P2 Core 파괴"};const dead=p=>s.towers.filter(t=>t.owner===p&&t.hp<=0).length;if(dead("P1")===3)return{winner:"P2",reason:"P1 타워 전멸"};if(dead("P2")===3)return{winner:"P1",reason:"P2 타워 전멸"};if(s.turn>MAX_TURNS){const score=p=>dead(foe(p)),hp=p=>s.towers.filter(t=>t.owner===p).reduce((n,t)=>n+Math.max(0,t.hp),0),uhp=p=>aliveUnits(s).filter(u=>u.owner===p).reduce((n,u)=>n+u.hp,0);if(score("P1")!==score("P2"))return{winner:score("P1")>score("P2")?"P1":"P2",reason:"60턴 파괴 점수"};if(hp("P1")!==hp("P2"))return{winner:hp("P1")>hp("P2")?"P1":"P2",reason:"60턴 타워 체력"};if(uhp("P1")!==uhp("P2"))return{winner:uhp("P1")>uhp("P2")?"P1":"P2",reason:"60턴 유닛 체력"};return{winner:null,reason:"60턴 완전 동률"}}return null}
function publicState(s){return{boardWidth:W,boardHeight:H,turn:s.turn,currentPlayer:s.currentPlayer,maxTurns:MAX_TURNS,energy:{...s.energy},hands:{P1:[...s.hands.P1],P2:[...s.hands.P2]},nextCards:{P1:s.queues.P1[0],P2:s.queues.P2[0]},units:aliveUnits(s).map(x=>({...x})),towers:s.towers.map(x=>({...x})),river:[...RIVER],bridges:[...BRIDGES],cards:CARDS,lastActions:[...s.lastActions],legalActions:legalActions(s,s.currentPlayer)}}
const workerSource=`self.onmessage=({data})=>{try{const f=new Function('"use strict";\\n'+data.code+'\\nif(typeof chooseAction!=="function")throw Error("chooseAction 함수를 찾을 수 없습니다.");return chooseAction;')();self.postMessage({ok:true,action:f(data.state,data.me)})}catch(e){self.postMessage({ok:false,error:e?.message||String(e)})}}`;
function askAI(code,s,me){return new Promise((resolve,reject)=>{const url=URL.createObjectURL(new Blob([workerSource],{type:"text/javascript"})),w=new Worker(url);URL.revokeObjectURL(url);const timer=setTimeout(()=>{w.terminate();reject(Error("행동 제한 시간 500ms 초과"))},500);w.onmessage=({data})=>{clearTimeout(timer);w.terminate();data.ok?resolve(data.action):reject(Error(data.error))};w.onerror=e=>{clearTimeout(timer);w.terminate();reject(Error(e.message))};w.postMessage({code,state:publicState(s),me})})}
function matchAction(actions,result){return actions.find(a=>a.id===(typeof result==="string"?result:result?.id))}function random(a){return a[Math.floor(Math.random()*a.length)]}
async function runGame(code,user,animate){let s=initial(),replay=[{state:clone(s),label:"게임 시작"}];startTurn(s);for(let i=0;i<MAX_TURNS+2;i++){const actions=legalActions(s,s.currentPlayer);let a=s.currentPlayer===user?matchAction(actions,await askAI(code,s,user)):chooseStrongActionV12(s,s.currentPlayer);if(!a)throw Error("legalActions에 없는 액션을 반환했습니다.");const label=actionText(s,a);s=applyAction(s,a);replay.push({state:clone(s),label});if(animate){state=s;render();await delay(100)}const end=outcome(s);if(end)return{...end,state:s,replay}}}
function actionText(s,a){return a.type==="pass"?`${s.currentPlayer} PASS`:`${s.currentPlayer} ${CARDS[a.cardId].icon} ${CARDS[a.cardId].name} @ ${a.position}`}
function render(){renderBoard();renderHud("P1");renderHud("P2");renderHand()}
function renderBoard(){const board=$("board"),valid=human&&state.currentPlayer==="P1"&&selectedCard?legalActions(state,"P1").filter(a=>a.cardId===selectedCard).map(a=>a.position):[];board.innerHTML="";for(let i=0;i<W*H;i++){const cell=document.createElement("div"),u=aliveUnits(state).find(x=>x.position===i),t=aliveTowers(state).find(x=>x.position===i);cell.className=`cell ${RIVER.includes(i)?"river":""} ${BRIDGES.includes(i)?"bridge":""} ${valid.includes(i)?"valid":""} ${i===lastCell?"last":""}`;const e=u||t;if(e){const span=document.createElement("span");span.className=`entity ${e.owner.toLowerCase()}`;span.textContent=u?CARDS[u.cardId].icon:TOWER_ICON[t.type];cell.appendChild(span);const hp=document.createElement("span");hp.className="hp";hp.innerHTML=`<b style="width:${Math.max(0,e.hp)/e.maxHp*100}%"></b>`;cell.appendChild(hp);if(u?.shield>0)cell.classList.add("shield")}if(valid.includes(i))cell.onclick=()=>humanPlay(i);board.appendChild(cell)}}
function renderHud(p){const el=$(p==="P1"?"p1Towers":"p2Towers");el.innerHTML=state.towers.filter(t=>t.owner===p).map(t=>`<i class="${t.hp<=0?"dead":""}">${TOWER_ICON[t.type]} ${Math.max(0,t.hp)}</i>`).join("");$(p==="P1"?"p1Energy":"p2Energy").textContent=`ENERGY ${state.energy[p]}/10`}
function renderHand(){const el=$("hand"),can=human&&state.currentPlayer==="P1";el.innerHTML="";for(const id of state.hands.P1){const c=CARDS[id],b=document.createElement("button");b.className=`card ${selectedCard===id?"selected":""}`;b.disabled=!can||c.cost>state.energy.P1;b.innerHTML=`<em>${c.cost}</em><b>${c.icon} ${c.name}</b><small>${c.desc}</small>`;b.onclick=()=>{selectedCard=id;$("guide").textContent="강조된 위치를 선택하세요.";render()};el.appendChild(b)}$("nextCard").textContent=`NEXT ${CARDS[state.queues.P1[0]].icon} ${CARDS[state.queues.P1[0]].name}`;$("pass").disabled=!can}
async function humanPlay(position){if(!human||!selectedCard)return;const a=legalActions(state,"P1").find(x=>x.cardId===selectedCard&&x.position===position);if(a)await humanAction(a)}
async function humanAction(a){const label=actionText(state,a);state=applyAction(state,a);lastReplay.push({state:clone(state),label});selectedCard=null;log(label);render();let end=outcome(state);if(end)return finishHuman(end);$("guide").textContent="강한 AI V12가 생각 중…";await delay(50);const ai=chooseStrongActionV12(state,"P2"),aiLabel=actionText(state,ai);state=applyAction(state,ai);lastReplay.push({state:clone(state),label:aiLabel});log(aiLabel);render();end=outcome(state);if(end)return finishHuman(end);$("guide").textContent="카드와 위치를 선택하거나 패스하세요.";$("status").textContent=`직접 플레이 · TURN ${state.turn}`}
function startHuman(){if(running)return;exitReplay();closeResult();state=initial();startTurn(state);human=true;selectedCard=null;lastReplay=[{state:clone(state),label:"직접 플레이 시작"}];$("p1Name").textContent="YOU · P1";$("autoBattle").disabled=true;$("status").textContent="직접 플레이 · TURN 1";$("guide").textContent="카드와 위치를 선택하거나 패스하세요.";$("log").innerHTML="";render()}
function stopGame(){human=false;selectedCard=null;state=initial();$("p1Name").textContent="YOUR AI · P1";$("autoBattle").disabled=false;$("status").textContent="대기 중";$("guide").textContent="모드를 선택하세요.";render()}
function finishHuman(end){human=false;$("autoBattle").disabled=false;const title=!end.winner?"무승부":end.winner==="P1"?"승리":"패배";showResult(title,`${end.reason} · TURN ${state.turn}`)}
async function tournament(){if(running)return;if(human)stopGame();exitReplay();closeResult();running=true;$("autoBattle").disabled=true;const code=$("editor").value.trim(),count=Number($("matchCount").value),rec={win:0,draw:0,loss:0};$("log").innerHTML="";try{if(!code)throw Error("AI 코드를 입력하세요.");for(let i=0;i<count;i++){const user=i%2?"P2":"P1";$("status").textContent=`${i+1}/${count} 경기 중`;const r=await runGame(code,user,count===1);lastReplay=r.replay;const key=!r.winner?"draw":r.winner===user?"win":"loss";rec[key]++;log(`GAME ${i+1} · ${user} · ${key.toUpperCase()} · ${r.reason}`);$("record").textContent=`${rec.win}승 ${rec.draw}무 ${rec.loss}패`;$("progressBar").style.width=(i+1)/count*100+"%";await delay(0)}const rate=Math.round(rec.win/count*100),title=rec.win>rec.loss?"AI 승리":rec.win<rec.loss?"AI 패배":"무승부";$("status").textContent="대전 완료";showResult(title,`${count}경기 · ${rec.win}승 ${rec.draw}무 ${rec.loss}패 · 승률 ${rate}%`);message(`대전 완료 · 승률 ${rate}%`,true)}catch(e){message(e.message);log("ERROR · "+e.message)}finally{running=false;$("autoBattle").disabled=false}}
function showResult(title,text){const type=title.includes("패배")?"loss":title.includes("무승부")?"draw":"win",card=$("result").querySelector(".result-card");card.className=`result-card ${type}`;$("resultIcon").textContent=type==="win"?"🏆":type==="loss"?"💥":"⚖️";$("resultTitle").textContent=title;$("resultText").textContent=text;$("result").hidden=false}function closeResult(){$("result").hidden=true}
function openReplay(){if(!lastReplay.length)return message("리플레이 기록이 없습니다.");closeResult();human=false;pauseReplay();replayIndex=0;$("replayControls").hidden=false;$("autoBattle").disabled=true;showFrame()}function showFrame(){const f=lastReplay[replayIndex];state=clone(f.state);selectedCard=null;render();$("replayCount").textContent=`${replayIndex+1}/${lastReplay.length}`;$("guide").textContent=f.label;$("status").textContent=`리플레이 · TURN ${state.turn}`}function stepReplay(d){replayIndex=Math.max(0,Math.min(lastReplay.length-1,replayIndex+d));showFrame();if(replayIndex===lastReplay.length-1)pauseReplay()}function toggleReplay(){if(replaying)return pauseReplay();if(replayIndex===lastReplay.length-1)replayIndex=0;replaying=true;$("playReplay").textContent="Ⅱ 정지";showFrame();replayTimer=setInterval(()=>stepReplay(1),600)}function pauseReplay(){replaying=false;if(replayTimer)clearInterval(replayTimer);replayTimer=null;if($("playReplay"))$("playReplay").textContent="▶ 재생"}function exitReplay(){pauseReplay();if($("replayControls"))$("replayControls").hidden=true;if($("autoBattle"))$("autoBattle").disabled=false}
function log(t){const li=document.createElement("li");li.textContent=t;$("log").appendChild(li);li.scrollIntoView({block:"nearest"})}function message(t,ok=false){$("message").textContent=t;$("message").style.color=ok?"var(--blue)":"var(--red)"}function normalize(t){const v=t.trim(),m=v.match(/^```(?:javascript|js)?\s*\n?([\s\S]*?)\n?```$/i);return(m?m[1]:v).trim()}function delay(ms){return new Promise(r=>setTimeout(r,ms))}
async function copyDocs(){try{const updated=docs.replace("- 덱 8장, 손패 4장. 카드를 사용하면 순환하고 패스하면 유지됩니다.","- 양측의 덱 8장은 경기마다 독립적으로 섞고 손패 4장을 뽑습니다. 카드를 사용하면 순환하고 패스하면 유지됩니다.");await navigator.clipboard.writeText(updated);message("LLM용 전체 문서를 복사했습니다.",true)}catch{message("클립보드가 차단되었습니다. 로컬 서버로 실행하세요.")}}async function pasteCode(){try{const c=normalize(await navigator.clipboard.readText());if(!c)throw Error();$("editor").value=c;localStorage.setItem("turn-card-ai",c);message("코드를 교체했습니다.",true)}catch{$("editor").focus();$("editor").select();message("지금 Ctrl+V를 누르세요.")}}
function renderCardGuide(){$("cardGuide").innerHTML=Object.entries(CARDS).map(([,c])=>`<div class="guide-card"><em>${c.cost}</em><b>${c.icon} ${c.name}</b><p>${c.desc}</p></div>`).join("")}
state=initial();$("editor").value=localStorage.getItem("turn-card-ai")||starterCode;$("editor").oninput=()=>localStorage.setItem("turn-card-ai",$("editor").value);$("copyDocs").onclick=copyDocs;$("paste").onclick=pasteCode;$("reset").onclick=()=>{$("editor").value=starterCode;localStorage.setItem("turn-card-ai",starterCode);message("예제 복원 완료",true)};$("autoBattle").onclick=tournament;$("humanStart").onclick=startHuman;$("stopGame").onclick=stopGame;$("pass").onclick=()=>humanAction({id:"pass",type:"pass"});$("clearLog").onclick=()=>$("log").innerHTML="";$("closeResult").onclick=closeResult;$("showReplay").onclick=openReplay;$("prev").onclick=()=>stepReplay(-1);$("next").onclick=()=>stepReplay(1);$("playReplay").onclick=toggleReplay;$("exitReplay").onclick=exitReplay;$("result").onclick=e=>{if(e.target===$("result"))closeResult()};renderCardGuide();render();
