import*as engine from"./engine.js";import*as ai from"./ai.js";import{mountArena}from"../arena-kit/app-shell.js";
const STARTER_AI_CODE=`function chooseAction(state, me) {
  const deliveries = state.legalActions
    .filter(action => action.type === "deliver")
    .sort((a, b) => (b.gain / Math.max(1, b.finish - state.couriers[me].time))
      - (a.gain / Math.max(1, a.finish - state.couriers[me].time)));
  return deliveries[0] || state.legalActions[0];
}`;
const SPEC=`[Chrono Courier AI 규격]\nchooseAction(state, me)를 작성하세요. couriers에는 time(0=08시, 12=20시), location, energy, score, completed, done이 있습니다. jobs는 공유 의뢰 4개이며 nextJob만 추가 공개합니다. deliver 행동에는 finish, gain, district, onTime, chain이 계산되어 있습니다. express는 에너지 1을 써 이동 1시간을 줄입니다. 같은 구역 연속 배송은 +2점, 마감 안 배송은 +2점입니다. rest는 1시간을 쓰고 에너지 +1, close는 하루를 마칩니다. legalActions 중 하나를 50KB/500ms 안에 동기 반환하세요.\n\n${STARTER_AI_CODE}`;
mountArena({gameId:"chrono-courier",title:"Chrono Courier",engine,ai,starterCode:STARTER_AI_CODE,spec:SPEC,codeFileName:"my-dispatcher.js",storageKey:"chrono-courier-ai",defaultOpponent:"v4",watchLevels:["v3","v5"],startMessage:"20시 전에 가장 가치 있는 배송 일정을 완성하세요.",turnMessage:s=>`${engine.formatTime(s.couriers.P1.time)} · 다음 목적지를 고르세요.`,emptyLog:"운행을 시작하면 시간표에 배송이 기록됩니다.",actionMarkup:a=>actionMarkup(a),renderGame:(s,c)=>renderGame(s,c)});
function renderGame(state,{mode,opponent}){return`<div class="dispatch-stage game-view"><section class="courier-board p1">${courierHtml(state,"P1",mode==="watch"?ai.AI_LEVELS.v3.name:"YOU")}</section><section class="job-board"><header><span>LIVE DISPATCH</span><b>공유 배송 의뢰</b></header><div class="district-map"><i>HUB</i><i>A</i><i>B</i><i>C</i><i>D</i></div><div class="jobs">${state.jobs.map(jobHtml).join("")}</div><div class="next-job">NEXT BOARD · ${state.jobDeck[0]?.name??"마지막 의뢰"}</div></section><section class="courier-board p2">${courierHtml(state,"P2",mode==="watch"?ai.AI_LEVELS.v5.name:opponent)}</section></div>`;}
function courierHtml(state,player,name){const c=state.couriers[player];return`<span class="route-id">ROUTE ${player}</span><h3>${name}</h3><strong>${c.score}<small> PT</small></strong><div class="clock"><span style="left:${c.time/engine.MAX_TIME*100}%"></span></div><div class="clock-label"><b>08</b><b>${engine.formatTime(c.time)}</b><b>20</b></div><dl><div><dt>현재 위치</dt><dd>${engine.DISTRICTS[c.location]}</dd></div><div><dt>특급 에너지</dt><dd>${"⚡".repeat(c.energy)||"—"}</dd></div><div><dt>완료 배송</dt><dd>${c.completed.length}</dd></div></dl><ol class="itinerary">${c.completed.length?c.completed.map(x=>`<li><time>${engine.formatTime(x.finish)}</time><b>${x.name}</b><span>+${x.gain}</span></li>`).join(""):"<li class=empty>비어 있는 일정표</li>"}</ol>`;}
function jobHtml(job){return`<article class="job-ticket"><span class="district">${job.district}</span><h4>${job.name}</h4><div><b>+${job.reward}</b> 기본</div><p>${job.duration}h 작업 · ${engine.formatTime(job.deadline)} 마감</p></article>`;}
function actionMarkup(a){if(a.type==="rest")return`<b>정비 휴식</b><span>1시간 · 특급 +1</span>`;if(a.type==="close")return`<b>오늘 운행 마감</b><span>현재 점수로 종료</span>`;return`<b>${a.express?"⚡ ":""}${a.name} → ${a.district}</b><span>${engine.formatTime(a.finish)} 도착 · +${a.gain}점${a.chain?" · 구역 체인":""}</span>`;}
